# Generated by Django 4.2.7 on 2024-01-07 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('is_split', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Households',
            fields=[
                ('household_id', models.AutoField(primary_key=True, serialize=False)),
                ('household_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_date', models.DateField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.households')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.items')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.receipts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('poll_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.households')),
            ],
        ),
        migrations.CreateModel(
            name='PollResponses',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.TextField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.polls')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
        ),
        migrations.CreateModel(
            name='Memberships',
            fields=[
                ('membership_id', models.AutoField(primary_key=True, serialize=False)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.households')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
        ),
        migrations.AddField(
            model_name='households',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users'),
        ),
        migrations.CreateModel(
            name='CalendarEvents',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.households')),
            ],
        ),
        migrations.CreateModel(
            name='BillShares',
            fields=[
                ('bill_share_id', models.AutoField(primary_key=True, serialize=False)),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.bills')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
        ),
        migrations.AddField(
            model_name='bills',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.households'),
        ),
    ]
